/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JFrame;
import qlsinhvientinhnguyen.HoatDong;
import qlsinhvientinhnguyen.Lop;
import qlsinhvientinhnguyen.Models;
import qlsinhvientinhnguyen.PhongVan;
import qlsinhvientinhnguyen.SinhVien;
import qlsinhvientinhnguyen.SinhVienPhongVan;
import qlsinhvientinhnguyen.SinhVienTinhNguyen;
import qlsinhvientinhnguyen.TaiKhoan;

/**
 *
 * @author ADMIN
 */
public class AppView extends javax.swing.JFrame {

    /**
     * Creates new form AppView
     */
    public AppView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnDangNhap = new javax.swing.JButton();
        btnDkiSVTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Thanh niên tình nguyện");

        btnDangNhap.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnDangNhap.setText("Đăng nhập");
        btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhapActionPerformed(evt);
            }
        });

        btnDkiSVTN.setText("Đăng ký phỏng vấn SV tình nguyện");
        btnDkiSVTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDkiSVTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(278, 278, 278)
                            .addComponent(btnDkiSVTN))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(182, 182, 182)
                            .addComponent(jLabel1))))
                .addContainerGap(159, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(97, 97, 97)
                .addComponent(btnDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDkiSVTN)
                .addContainerGap(141, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDkiSVTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDkiSVTNActionPerformed
        DangKyView dangKiView = new DangKyView();
        dangKiView.setLocationRelativeTo(null);
        dangKiView.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        dangKiView.setVisible(true);
        
        Models models = new Models();
        ArrayList<Lop> ListLop = new ArrayList<Lop>();
        ListLop.add(new Lop("IT01", "KHMT01", 15, "CNTT"));
        ListLop.add(new Lop("IT02", "HTTT1", 15, "CNTT"));
        ListLop.add(new Lop("IT03", "CNTT1", 15, "CNTT"));
        ListLop.add(new Lop("IT04", "KTPM1", 15, "CNTT"));
        
        
        ArrayList<PhongVan> ListPV = new ArrayList<PhongVan>();
        ListPV.add(new PhongVan("PV01", LocalDate.of(2023, 3, 5), "305 - A10", 10));
        ListPV.add(new PhongVan("PV02", LocalDate.of(2023, 5, 8), "305 - A10", 5));
        
        
        ArrayList<TaiKhoan> ListTK = new ArrayList<TaiKhoan>();
        ListTK.add(new TaiKhoan("admin", "admin", 1));
        ListTK.add(new TaiKhoan("SV01", "123456", 2));
        ListTK.add(new TaiKhoan("SV03", "123456", 2));
        ListTK.add(new TaiKhoan("SV04", "123456", 2));
        ListTK.add(new TaiKhoan("SV07", "123456", 2));
        
        
        ArrayList<SinhVien> ListSV = new ArrayList<SinhVien>();
        ListSV.add(new SinhVienTinhNguyen("SV01", "Nguyễn Ngọc Xuân",   ListLop.get(0), "0325524413", "xuannn@gmail.com",       ListTK.get(1), "Thành viên"));
        ListSV.add(new SinhVienPhongVan  ("SV02", "Trần Anh Tuyền",     ListLop.get(1), "0543524512", "anhtuyen@gmail.com",     null));
        ListSV.add(new SinhVienTinhNguyen("SV03", "Phạm Xuân Long",     ListLop.get(2), "0343523134", "long@gmail.com",         ListTK.get(2), "Thành viên"));
        ListSV.add(new SinhVienTinhNguyen("SV04", "Hà Thanh Huyền",     ListLop.get(3), "0235524454", "thanhhuyen@gmail.com",   ListTK.get(3), "Thành viên"));
        ListSV.add(new SinhVienPhongVan  ("SV05", "Phạm Tuấn Anh",      ListLop.get(3), "0225532417", "letgo@gmail.com",        null));
        ListSV.add(new SinhVienPhongVan  ("SV06", "Hoàng Văn Ngọc",     ListLop.get(2), "0924524416", "ngochoang@gmail.com",    null));
        ListSV.add(new SinhVienTinhNguyen("SV07", "Trần Đức Đạt",       ListLop.get(1), "0334525410", "ducdat342@gmail.com",    ListTK.get(4), "Thành viên"));
        ListSV.add(new SinhVienPhongVan  ("SV08", "Đào Thị Thảo",    ListLop.get(2), "0325524311", "daothithao@gmail.com",    null));
        ListSV.add(new SinhVienPhongVan  ("SV09", "Lưu Tuấn Thành",    ListLop.get(1), "0325524311", "tuanthanh@gmail.com",    null));
        ListSV.add(new SinhVienPhongVan  ("SV10", "Phạm Nguyễn Nguyên Hải",    ListLop.get(0), "0325524311", "nguyenhai@gmail.com",    null));
        ListSV.add(new SinhVienPhongVan  ("SV11", "Tạ Đức Mạnh",    ListLop.get(3), "0325524311", "ducmanh@gmail.com",    null));
        ListSV.add(new SinhVienPhongVan  ("SV12", "Nguyễn Thị Thông",    ListLop.get(2), "0325524311", "nguyenthong@gmail.com",    null));
        ListSV.add(new SinhVienPhongVan  ("SV13", "Trần Duy Long",    ListLop.get(0), "0325524311", "duylong@gmail.com",    null));
        ListSV.add(new SinhVienPhongVan  ("SV14", "Nguyễn Bá Trung",    ListLop.get(1), "0325524311", "batrung@gmail.com",    null));
        
        
        ArrayList<HoatDong> ListHD = new ArrayList<HoatDong>();
        ListHD.add(new HoatDong("HD01", "Dọn vệ sinh trường", LocalDate.of(2023, 6, 15), "Dọn dẹp toàn bộ khuôn viên trường, các phòng học", "Nguyễn Xuân Anh", 5000000));
        ListHD.add(new HoatDong("HD02", "Tổ chức hiến máu", LocalDate.of(2023, 6, 18), "Phân công hỗ trợ tổ chức hiến máu tình nguyện", "Nguyễn Nam Anh", 1000000));
        ListHD.add(new HoatDong("HD03", "Tổ chức sự kiện VWA", LocalDate.of(2023, 7, 10), "Dọn dẹp toàn bộ khán đài, bàn ghế khách", "Hà Thanh Hoàng", 2000000));
        ListHD.add(new HoatDong("HD04", "Tổ chức sự kiện VNH", LocalDate.of(2023, 7, 15), "Dọn dẹp toàn bộ khán đài, bàn ghế khách", "Nguyễn Xuân Anh", 2000000));
        
        
        models.setListLops(ListLop);
        models.setListPhongVans(ListPV);
        models.setListTaiKhoans(ListTK);
        models.setListSinhViens(ListSV);
        models.setListHoatDongs(ListHD);
        try{
            models.SaveChange();
            System.out.print("ThanhCongg");
        }
        catch(Exception ex){
            System.out.println(ex.toString());
        }
    }//GEN-LAST:event_btnDkiSVTNActionPerformed

    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed
        DangNhapView dnv = new DangNhapView();
        dnv.setLocationRelativeTo(null);
        dnv.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        dnv.setVisible(true);
    }//GEN-LAST:event_btnDangNhapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangNhap;
    private javax.swing.JButton btnDkiSVTN;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
