/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import qlsinhvientinhnguyen.Models;
import qlsinhvientinhnguyen.PhongVan;
import qlsinhvientinhnguyen.SinhVien;
import qlsinhvientinhnguyen.SinhVienPhongVan;
import javax.swing.JOptionPane;
import java.awt.FlowLayout;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import qlsinhvientinhnguyen.SinhVienTinhNguyen;

/**
 *
 * @author T490
 */
public class DangKyView extends javax.swing.JFrame {

    /**
     * Creates new form DangKyView
     */
    Models model = new Models();
    String selectCB;
    int soLuongThamGia;
    boolean found;
    boolean clickKT = false;
    private static DangKyView instance;

    public DangKyView() {
        initComponents();
        try {
            model.Import();
            loadList();
            ArrayList<String> ngayphongvan = new ArrayList<>();
            //loadCombobox(ngayphongvan);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }

    }

    private ArrayList<PhongVan> getNgayPhongVanList() {
        ArrayList<PhongVan> ngayphongvan = new ArrayList<>();
        for (PhongVan i : model.getListPhongVans()) {
            if (i instanceof PhongVan) {
                ngayphongvan.add(i);
            }
        }
        return ngayphongvan;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        MaSVText = new javax.swing.JTextField();
        HoTenText = new javax.swing.JTextField();
        LopText = new javax.swing.JTextField();
        ThoiGianCB = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        btnThoat = new javax.swing.JButton();
        btnGuiYeuCau = new javax.swing.JButton();
        btnKiemTra = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        btnRefresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Đăng ký phỏng vấn");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Họ tên:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Mã SV:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Lớp:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Thời gian:");

        MaSVText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MaSVText.setToolTipText("");
        MaSVText.setName("inputmasv"); // NOI18N
        MaSVText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaSVTextActionPerformed(evt);
            }
        });

        HoTenText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        HoTenText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HoTenTextActionPerformed(evt);
            }
        });

        LopText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        ThoiGianCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThoiGianCBActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Các phòng phỏng vấn hiện có:");
        jLabel6.setToolTipText("");

        btnThoat.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        btnGuiYeuCau.setBackground(new java.awt.Color(0, 0, 0));
        btnGuiYeuCau.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGuiYeuCau.setForeground(new java.awt.Color(255, 255, 255));
        btnGuiYeuCau.setText("Gửi yêu cầu");
        btnGuiYeuCau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuiYeuCauActionPerformed(evt);
            }
        });

        btnKiemTra.setText("Kiểm Tra");
        btnKiemTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKiemTraActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(jList1);

        btnRefresh.setText("Làm mới");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 409, Short.MAX_VALUE)
                        .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(185, 185, 185))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(118, 118, 118)
                                .addComponent(btnGuiYeuCau, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(MaSVText, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnKiemTra))
                            .addComponent(LopText, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HoTenText, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ThoiGianCB, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRefresh)))
                        .addGap(31, 31, 31))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(279, 279, 279))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MaSVText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKiemTra, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HoTenText, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LopText, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ThoiGianCB, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuiYeuCau, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRefresh)
                        .addGap(22, 22, 22)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HoTenTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HoTenTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HoTenTextActionPerformed

    private void MaSVTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaSVTextActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_MaSVTextActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnGuiYeuCauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuiYeuCauActionPerformed
        // TODO add your handling code here:

        if (clickKT) {
            int dem = 0;
            try {
                for (PhongVan i : model.getListPhongVans()) {
                    if (i.getNgayPV().toString().equals(selectCB)) {
                        for (SinhVien sv : model.getListSinhViens()) {
                            if (sv instanceof SinhVienPhongVan) {
                                SinhVienPhongVan sinhvienphongvan = (SinhVienPhongVan) sv;
                                if (sinhvienphongvan.getMaSV().equals(MaSVText.getText()) && sinhvienphongvan.getPhongVan() == null) {
                                    if (i.getSoLuongThamGia() < i.getSoLuong()) {
                                        soLuongThamGia = i.getSoLuongThamGia();
                                        i.setSoLuongThamGia(++soLuongThamGia);
                                        sinhvienphongvan.setPhongVan(i);
                                        model.SaveChange();
                                        JOptionPane.showMessageDialog(null, "Gửi yêu cầu thành công!");

                                    } else {
                                        JOptionPane.showMessageDialog(null, "Đã nhận đủ số lượng phỏng vấn ngày " + i.getNgayPV());
                                    }

                                } else if (sinhvienphongvan.getMaSV().equals(MaSVText.getText()) && sinhvienphongvan.getPhongVan() != null) {
                                    JOptionPane.showMessageDialog(null, "Sinh viên đã gửi yêu cầu trước đó!");
                                }
                            }
                        }
                    }
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.toString());
            }
            refreshList();
            for (SinhVien i : model.getListSinhViens()) {
                if (i instanceof SinhVienPhongVan) {
                    SinhVienPhongVan svpvvv = (SinhVienPhongVan) i;
                    if (svpvvv.getPhongVan() != null) {
                        ++dem;
                    }
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Kiểm tra thông tin trước khi gửi!");
        }
        clickKT = false;
    }//GEN-LAST:event_btnGuiYeuCauActionPerformed

    private void btnKiemTraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKiemTraActionPerformed
        // TODO add your handling code here:
        found = false;
        String maSV = MaSVText.getText();
        ArrayList<SinhVien> svpv = new ArrayList<SinhVien>();
        svpv = model.getListSinhViens();
        // String hoTen = jTextField2.getText();
        // String lop = jTextField3.getText();

        for (SinhVien sv : svpv) {
            if (sv instanceof SinhVienPhongVan) {
                SinhVienPhongVan sinhvienphongvan = (SinhVienPhongVan) sv;//ép  từ sinh viên về sinh viên phỏng vấn
                if (!checkSVTN(maSV)) {
                    if (maSV.equals(sinhvienphongvan.getMaSV())) {
                        found = true;
                        clickKT = true;
                        HoTenText.setText(sinhvienphongvan.getTenSV());
                        LopText.setText(sinhvienphongvan.getLop().getTenLop());
                        loadConboBox();
                        break;
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Sinh viên đã là sinh viên tình nguyện");
                    found = true;
                    HoTenText.setText("");
                    LopText.setText("");
                    ThoiGianCB.removeAllItems();
                    break;
                }
            }
        }

        if (!found) {
            // Dữ liệu đã tồn tại
            JOptionPane.showMessageDialog(null, "Không tồn tại sinh viên!");
            HoTenText.setText("");
            LopText.setText("");
            ThoiGianCB.removeAllItems();
        }
    }//GEN-LAST:event_btnKiemTraActionPerformed

    public void refreshList() {
        try {
            model.Import();
            updateList();
            jList1.repaint();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    private boolean checkSVTN(String masv) {
        for (SinhVien sv : model.getListSinhViens()) {
            if (sv instanceof SinhVienTinhNguyen) {
                SinhVienTinhNguyen sinhvientinhnguyen = (SinhVienTinhNguyen) sv;
                if (masv.equals(sinhvientinhnguyen.getMaSV())) {
                    return true;
                }
            }
        }
        return false;
    }

    private void ThoiGianCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThoiGianCBActionPerformed
        // TODO add your handling code here:
        selectCB = (String) ThoiGianCB.getSelectedItem();
    }//GEN-LAST:event_ThoiGianCBActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
      //  refreshList();
    }//GEN-LAST:event_btnRefreshActionPerformed
    private void loadConboBox() {
        ThoiGianCB.removeAllItems();
        for (PhongVan i : model.getListPhongVans()) {
            ThoiGianCB.addItem(i.getNgayPV().toString());
        }
    }

    private void loadList() {

        DefaultListModel<String> listModel1 = new DefaultListModel<>();
        for (PhongVan item : model.getListPhongVans()) {
            listModel1.addElement(item.getNgayPV() + ": Phỏng vấn " + item.getSoLuong()
                    + " người tại phòng " + item.getPhongPV() + ": " + item.getSoLuongThamGia() + "/" + item.getSoLuong());

        }
        jList1.setModel(listModel1);
    }

    private void updateList() {
        DefaultListModel<String> listModel = (DefaultListModel<String>) jList1.getModel();
        listModel.clear(); // Xóa sạch danh sách hiện tại

        // Thêm lại các phần tử đã được cập nhật giá trị SoLuongThamGia
        for (PhongVan item : model.getListPhongVans()) {
            listModel.addElement(item.getNgayPV() + ": Phỏng vấn " + item.getSoLuong()
                    + " người tại phòng " + item.getPhongPV() + ": " + item.getSoLuongThamGia() + "/" + item.getSoLuong());
        }
    }

    public static DangKyView getInstance() {
        if (instance == null) {
            instance = new DangKyView();
        }
        return instance;
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangKyView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangKyView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangKyView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangKyView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DangKyView().getInstance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField HoTenText;
    private javax.swing.JTextField LopText;
    private javax.swing.JTextField MaSVText;
    private javax.swing.JComboBox<String> ThoiGianCB;
    private javax.swing.JButton btnGuiYeuCau;
    private javax.swing.JButton btnKiemTra;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnThoat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

}
