/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import qlsinhvientinhnguyen.DanhGia;
import qlsinhvientinhnguyen.HoatDong;
import qlsinhvientinhnguyen.Models;
import qlsinhvientinhnguyen.SinhVien;
import qlsinhvientinhnguyen.SinhVienTinhNguyen;

/**
 *
 * @author An Viet Computer
 */
public class DanhGiaHoatDong extends javax.swing.JFrame {

    /**
     * Creates new form DanhGiaHoatDong
     */
    Models model = new Models();
    HoatDong hoatDongDanhGia = null;
    SinhVienTinhNguyen svtnDanhGia = null;
     private static DanhGiaHoatDong instance;
    public DanhGiaHoatDong() {
        try{
            model.Import();
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }
    
    public DanhGiaHoatDong(HoatDong hoatDongSelected, SinhVienTinhNguyen sinhVienTNSelected ) {
        initComponents();
        try{
            model.Import();
            hoatDongDanhGia = hoatDongSelected;
            svtnDanhGia = sinhVienTNSelected;
            sao_5.setSelected(true);
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtNoiDungDanhGia = new javax.swing.JTextArea();
        btnGui = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        sao_4 = new javax.swing.JRadioButton();
        sao_3 = new javax.swing.JRadioButton();
        sao_2 = new javax.swing.JRadioButton();
        sao_1 = new javax.swing.JRadioButton();
        sao_5 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1200, 600));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Đánh giá hoạt động");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Đánh giá: ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Nội dung: ");

        txtNoiDungDanhGia.setColumns(20);
        txtNoiDungDanhGia.setRows(5);
        jScrollPane1.setViewportView(txtNoiDungDanhGia);

        btnGui.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnGui.setText("Gửi");
        btnGui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuiActionPerformed(evt);
            }
        });

        btnThoat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        buttonGroup1.add(sao_4);
        sao_4.setText("4/5");
        sao_4.setName("cbdanhgia"); // NOI18N

        buttonGroup1.add(sao_3);
        sao_3.setText("3/5");
        sao_3.setName("cbdanhgia"); // NOI18N

        buttonGroup1.add(sao_2);
        sao_2.setText("2/5");
        sao_2.setName("cbdanhgia"); // NOI18N

        buttonGroup1.add(sao_1);
        sao_1.setText("1/5");
        sao_1.setName("cbdanhgia"); // NOI18N

        buttonGroup1.add(sao_5);
        sao_5.setText("5/5");
        sao_5.setName("cbdanhgia"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(485, Short.MAX_VALUE)
                .addComponent(btnGui)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnThoat)
                .addGap(174, 174, 174))
            .addGroup(layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
                        .addGap(174, 174, 174))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(sao_5)
                        .addGap(34, 34, 34)
                        .addComponent(sao_4)
                        .addGap(29, 29, 29)
                        .addComponent(sao_3)
                        .addGap(35, 35, 35)
                        .addComponent(sao_2)
                        .addGap(36, 36, 36)
                        .addComponent(sao_1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(291, 291, 291)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(sao_4)
                    .addComponent(sao_3)
                    .addComponent(sao_2)
                    .addComponent(sao_1)
                    .addComponent(sao_5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnThoat)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnGui, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnGuiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuiActionPerformed
        DanhGia dg = new DanhGia();
        if(sao_5.isSelected())
            dg.setSoSaoDanhGia(5);
        else if(sao_4.isSelected())
            dg.setSoSaoDanhGia(4);
        else if(sao_3.isSelected())
            dg.setSoSaoDanhGia(3);
        else if(sao_2.isSelected())
            dg.setSoSaoDanhGia(2);
        else
            dg.setSoSaoDanhGia(1);
        dg.setNoiDungDanhGia(txtNoiDungDanhGia.getText());
        try{
            for(HoatDong i : model.ListHoatDongs){
                if(i.getMaHD().equals(hoatDongDanhGia.getMaHD())){
                    for(SinhVienTinhNguyen j : i.getDSSinhVienThamGia()){
                        if(j.getMaSV().equals(svtnDanhGia.getMaSV())){
                            j.setDanhGia(dg);
                            model.SaveChange();
                            JOptionPane.showMessageDialog(null, "Cảm ơn bạn đã đánh giá hoạt động");
                            break;
                        }
                    }
                    break;
                }
            }
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
        dispose();
    }//GEN-LAST:event_btnGuiActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnThoatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static DanhGiaHoatDong getInstance() {
        if (instance == null) {
            instance = new DanhGiaHoatDong();
        }
        return instance;
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DanhGiaHoatDong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DanhGiaHoatDong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DanhGiaHoatDong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DanhGiaHoatDong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DanhGiaHoatDong().getInstance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGui;
    private javax.swing.JButton btnThoat;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton sao_1;
    private javax.swing.JRadioButton sao_2;
    private javax.swing.JRadioButton sao_3;
    private javax.swing.JRadioButton sao_4;
    private javax.swing.JRadioButton sao_5;
    private javax.swing.JTextArea txtNoiDungDanhGia;
    // End of variables declaration//GEN-END:variables
}
