/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import qlsinhvientinhnguyen.HoatDong;
import qlsinhvientinhnguyen.Models;
import qlsinhvientinhnguyen.SinhVien;
import qlsinhvientinhnguyen.SinhVienTinhNguyen;

/**
 *
 * @author T490
 */
public class DanhSachSVThamGia_Admin extends javax.swing.JFrame {

    /**
     * Creates new form DanhSachSVThamGia_Admin
     */
    HoatDong hoatDongHienTai = null;
    Models model = new Models();
    ArrayList<SinhVienTinhNguyen> listSVTN;
    SinhVienTinhNguyen svtnSelected = null;
    SinhVienTinhNguyen svtgSelected = null;
    private static DanhSachSVThamGia_Admin instance;
    
    public DanhSachSVThamGia_Admin() {
        initComponents();
        try{
            model.Import();
            
            listSVTN = new ArrayList<SinhVienTinhNguyen>();
            for(SinhVien i : model.getListSinhViens())
                if(i instanceof SinhVienTinhNguyen)
                    listSVTN.add((SinhVienTinhNguyen)i);
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }
    
    public DanhSachSVThamGia_Admin(HoatDong hoatDongSelected) {
        initComponents();
        try{
            model.Import();
            for(HoatDong i : model.getListHoatDongs()){
                if(i.getMaHD().equals(hoatDongSelected.getMaHD())){
                    hoatDongHienTai = i;
                    break;
                }
            }
            
            listSVTN = new ArrayList<SinhVienTinhNguyen>();
            for(SinhVien i : model.getListSinhViens())
                if(i instanceof SinhVienTinhNguyen)
                    listSVTN.add((SinhVienTinhNguyen)i);
            
            LoadTable1();
            LoadTable2();
            LoadThongTinHoatDong();
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
        
    }
    
    public void LoadTable1(){
        DefaultTableModel modelTable1 =  (DefaultTableModel)DSSVTNtable.getModel();
        modelTable1.setRowCount(0);
        int dem = 0;
        if(hoatDongHienTai.getDSSinhVienThamGia().isEmpty()){
            for(SinhVienTinhNguyen i : listSVTN){           
                modelTable1.addRow(new Object[]{
                    ++dem, i.getMaSV(), i.getTenSV(), i.getLop().getTenLop(), i.getSDT()
                });
            }   
        }
        else{
//            for(SinhVienTinhNguyen i : listSVTN){      
//                if(hoatDongHienTai.getDSSinhVienThamGia().contains(i)){
//                    modelTable1.addRow(new Object[]{
//                        ++dem, i.getMaSV(), i.getTenSV(), i.getLop().getTenLop(), i.getSDT()
//                    });
//                }
//            } 
            for (SinhVienTinhNguyen i : listSVTN) {
                boolean isExist = false;
                for (SinhVienTinhNguyen j : hoatDongHienTai.getDSSinhVienThamGia()) {
                    if (i.getMaSV().equals(j.getMaSV())) {
                        isExist = true;
                        break;
                    }
                }
                if (!isExist) {
                    modelTable1.addRow(new Object[]{
                        ++dem, i.getMaSV(), i.getTenSV(), i.getLop().getTenLop(), i.getSDT()
                    });
                }
            } 
        }
    }
    
    public void LoadTable2(){
        DefaultTableModel modelTable2 =  (DefaultTableModel)DSSVTNThamGiatable.getModel();
        modelTable2.setRowCount(0);
        int dem = 0;
        for(SinhVienTinhNguyen i : hoatDongHienTai.getDSSinhVienThamGia()){           
            modelTable2.addRow(new Object[]{
                ++dem, i.getMaSV(), i.getTenSV(), i.getLop().getTenLop(), i.getSDT()
            });
        }
    }
    
    public void LoadThongTinHoatDong(){
        txtTenHDHienTai.setText(hoatDongHienTai.getTenHD());
        txtNgayBatDauHienTai.setText(hoatDongHienTai.getNgayBatDau().getDayOfMonth() + "-" + hoatDongHienTai.getNgayBatDau().getMonthValue()+ "-" + hoatDongHienTai.getNgayBatDau().getYear());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DSSVTNtable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        DSSVTNThamGiatable = new javax.swing.JTable();
        btnChuyen = new java.awt.Button();
        btnXoa = new java.awt.Button();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        jLabel7 = new javax.swing.JLabel();
        txtNgayBatDauHienTai = new java.awt.TextField();
        txtTenHDHienTai = new java.awt.TextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Danh sách sinh viên tình nguyện tham gia hoạt động");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Tên họat động : ");

        DSSVTNtable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DSSVTNtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã SV", "Tên SV", "Lớp", "Số điện thoại"
            }
        ));
        DSSVTNtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table1RowSelected(evt);
            }
        });
        jScrollPane1.setViewportView(DSSVTNtable);
        if (DSSVTNtable.getColumnModel().getColumnCount() > 0) {
            DSSVTNtable.getColumnModel().getColumn(0).setMinWidth(10);
            DSSVTNtable.getColumnModel().getColumn(0).setMaxWidth(35);
            DSSVTNtable.getColumnModel().getColumn(1).setMinWidth(15);
            DSSVTNtable.getColumnModel().getColumn(1).setMaxWidth(50);
            DSSVTNtable.getColumnModel().getColumn(3).setMinWidth(30);
            DSSVTNtable.getColumnModel().getColumn(3).setMaxWidth(70);
        }

        DSSVTNThamGiatable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DSSVTNThamGiatable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã SV", "Tên SV", "Lớp", "Số điện thoại"
            }
        ));
        DSSVTNThamGiatable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table2RowSelected(evt);
            }
        });
        jScrollPane2.setViewportView(DSSVTNThamGiatable);
        if (DSSVTNThamGiatable.getColumnModel().getColumnCount() > 0) {
            DSSVTNThamGiatable.getColumnModel().getColumn(0).setMinWidth(10);
            DSSVTNThamGiatable.getColumnModel().getColumn(0).setMaxWidth(35);
            DSSVTNThamGiatable.getColumnModel().getColumn(1).setMinWidth(15);
            DSSVTNThamGiatable.getColumnModel().getColumn(1).setMaxWidth(50);
            DSSVTNThamGiatable.getColumnModel().getColumn(3).setMinWidth(30);
            DSSVTNThamGiatable.getColumnModel().getColumn(3).setMaxWidth(70);
        }

        btnChuyen.setLabel("Chuyển");
        btnChuyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChuyenActionPerformed(evt);
            }
        });

        btnXoa.setLabel("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        label1.setText("Danh sách Sinh viên tình nguyện");

        label2.setText("Danh sách tham gia hoạt động");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Ngày bắt đầu : ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(165, 165, 165)
                        .addComponent(btnChuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 46, Short.MAX_VALUE)
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(178, 178, 178)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTenHDHienTai, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(jLabel7)
                .addContainerGap(309, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtNgayBatDauHienTai, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(132, 132, 132))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(txtNgayBatDauHienTai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTenHDHienTai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnChuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChuyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChuyenActionPerformed
        try{
            if(svtnSelected != null){
                hoatDongHienTai.getDSSinhVienThamGia().add(svtnSelected);
                model.SaveChange();
                LoadTable1();
                LoadTable2();
            }
            else{
                throw new Exception("Chưa có sinh viên tình nguyện nào được chọn để thêm");
            }
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }//GEN-LAST:event_btnChuyenActionPerformed

    private void table1RowSelected(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table1RowSelected
        DefaultTableModel modelTab = (DefaultTableModel) DSSVTNtable.getModel();
        int selectedRow = DSSVTNtable.getSelectedRow();
        if(selectedRow != -1){
            Object value = modelTab.getValueAt(selectedRow, 1);
            String MaSVSelected = "";
            if(value != null){
                MaSVSelected = (String)value;
            }
            
//            svtnSelected = listSVTN.get(selectedRow);
            for(SinhVienTinhNguyen i : listSVTN){
                if(i.getMaSV().equals(MaSVSelected)){
                    svtnSelected = new SinhVienTinhNguyen(i.getMaSV(), i.getTenSV(), i.getLop(), i.getSDT(), i.getEmail(), i.getTaiKhoan(), i.getVaiTro());
//                    svtgSelected = i;
                    break;
                }
            }
        }
    }//GEN-LAST:event_table1RowSelected

    private void table2RowSelected(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table2RowSelected
        int selectedRow = DSSVTNThamGiatable.getSelectedRow();
        if(selectedRow != -1){
            svtgSelected = hoatDongHienTai.getDSSinhVienThamGia().get(selectedRow);
        }
    }//GEN-LAST:event_table2RowSelected

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        try{
            if(svtgSelected != null){
                hoatDongHienTai.getDSSinhVienThamGia().remove(svtgSelected);
                model.SaveChange();
                LoadTable1();
                LoadTable2();
            }
            else{
                throw new Exception("Chưa có sinh viên tình nguyện nào được chọn để xóa");
            }
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    /**
     * @param args the command line arguments
     */
     public static DanhSachSVThamGia_Admin getInstance() {
        if (instance == null) {
            instance = new DanhSachSVThamGia_Admin();
        }
        return instance;
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DanhSachSVThamGia_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DanhSachSVThamGia_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DanhSachSVThamGia_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DanhSachSVThamGia_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DanhSachSVThamGia_Admin().getInstance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable DSSVTNThamGiatable;
    private javax.swing.JTable DSSVTNtable;
    private java.awt.Button btnChuyen;
    private java.awt.Button btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.TextField txtNgayBatDauHienTai;
    private java.awt.TextField txtTenHDHienTai;
    // End of variables declaration//GEN-END:variables
}
